import smtplib
from email.message import EmailMessage

from app.admin_portal.core.config import settings


# =========================================================
# INTERNAL EMAIL SENDER
# =========================================================

def _send_email(
    recipient_email: str,
    subject: str,
    body: str,
    reply_to: str | None = None,
) -> None:
    """
    Internal helper used to send an email through
    the configured Gmail SMTP server.
    """

    message = EmailMessage()

    message["Subject"] = subject

    message["From"] = (
        f"{settings.SMTP_FROM_NAME} "
        f"<{settings.SMTP_FROM_EMAIL}>"
    )

    message["To"] = recipient_email
    if reply_to:
        message["Reply-To"] = reply_to

    message.set_content(body.strip())

    with smtplib.SMTP(
        settings.SMTP_HOST,
        settings.SMTP_PORT,
    ) as server:

        server.starttls()

        server.login(
            settings.SMTP_USERNAME,
            settings.SMTP_PASSWORD,
        )

        server.send_message(message)


def send_support_inquiry_email(
    recipient_email: str,
    *,
    name: str,
    sender_email: str,
    subject: str,
    message: str,
) -> None:
    """Notify an administrator of a website inquiry; replies go to the sender."""
    safe_subject = " ".join(subject.splitlines()).strip()
    body = f"""A new message was submitted through the EPS-TOPIK website.

From: {name}
Email: {sender_email}
Subject: {subject}

Message:
{message}
"""
    _send_email(
        recipient_email=recipient_email,
        subject=f"Website inquiry: {safe_subject}",
        body=body,
        reply_to=sender_email,
    )


def send_admin_inquiry_reply(
    recipient_email: str,
    *,
    student_name: str,
    admin_name: str,
    admin_email: str,
    subject: str,
    reply: str,
) -> None:
    """Send an administrator's response to a student inquiry."""
    safe_subject = " ".join(subject.splitlines()).strip()
    body = f"""Hello {student_name},

{reply.strip()}

Regards,
{admin_name}
EPS-TOPIK Admin Team
"""
    _send_email(
        recipient_email=recipient_email,
        subject=f"Re: {safe_subject}",
        body=body,
        reply_to=admin_email,
    )


# =========================================================
# ADMIN CREATION / EMAIL VERIFICATION OTP
# =========================================================

def send_otp_email(
    recipient_email: str,
    otp: str,
) -> None:
    """
    Sends a verification OTP to the recipient.

    Currently used for:
    - Creating a new Admin account
    - Other email verification flows
    """

    body = f"""
Hello,

Your EPS-TOPIK Admin Portal verification code is:

{otp}

This verification code will expire shortly.

If you did not request this code,
you can safely ignore this email.

Regards,
{settings.SMTP_FROM_NAME}
"""

    _send_email(
        recipient_email=recipient_email,
        subject="EPS-TOPIK Admin Verification Code",
        body=body,
    )


# =========================================================
# ADMIN PASSWORD RESET OTP
# =========================================================

def send_admin_forgot_password_email(
    recipient_email: str,
    otp: str,
) -> None:
    """
    Sends a 6-digit OTP for Admin password recovery.

    The OTP is generated by the authentication route.
    Only the hashed OTP is stored in the database.
    """

    body = f"""
Hello Admin,

A password reset was requested for your
EPS-TOPIK Admin Portal account.

Your 6-digit password reset OTP is:

{otp}

This OTP will expire shortly and can only be used once.

IMPORTANT:

- Do not share this OTP with anyone.
- If you did not request a password reset,
  you can safely ignore this email.
- Your current password will remain unchanged
  unless the reset process is successfully completed.

Regards,
{settings.SMTP_FROM_NAME}
"""

    _send_email(
        recipient_email=recipient_email,
        subject="EPS-TOPIK Admin Password Reset OTP",
        body=body,
    )
